### ISSUE TITLE
Last byte of `z32`-encoded string encoded in multiple ways

### ISSUE THREAD

**Issue by josephmturner** [mafintosh/z32#3]
As described [here](https://github.com/RangerMauve/hypercore-fetch/issues/58), `sw8dj5y9cs5nb8dzq1h9tbjt3b4u3sci6wfeckbsch9w3q7amipy` and `sw8dj5y9cs5nb8dzq1h9tbjt3b4u3sci6wfeckbsch9w3q7amipb` (last character changed from `y` to `b`) appear to encode the same value. Is this the expected behavior?

Thank you!

**Comment by mafintosh** [comment]
Yep, it’s because each char is 5bits so you are changing bits that are ignored when decoding as it’s truncated

**Comment by josephmturner** [comment]
Thank you for explaining!
